"""
lot_curation.py — propose OSM-lot <-> inventory-zone matches for human review.

The off-street OSM measurement (osm-lots.json) counts ALL owners (~3,380 spaces);
the inventory's 5 public rear-lot zones (~443) are the curated public subset.
Closing that gap means deciding WHICH OSM lots are the public ones. OSM has no
access tags, so this can't be fully automated. What this DOES, safely:

  for each inventory public-lot zone, geocode its real-world reference, find the
  nearest OSM public-candidate lot, and PROPOSE a match with the measured spaces,
  the hand estimate, the walk gap, and a confidence. Output is a worksheet a
  human confirms -- NOT an automatic overwrite of inventory/data.ts.

Run:
  cd analysis
  VIRTUAL_ENV="$(pwd)/.venv-osm" .venv-osm/bin/python lot_curation.py
Writes: analysis/out/lot-curation-worksheet.md
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import osmnx as ox

ROOT = Path(__file__).resolve().parent.parent
LOTS = json.load(open(ROOT / "src" / "lib" / "inventory" / "osm-lots.json"))
OUT = Path(__file__).resolve().parent / "out" / "lot-curation-worksheet.md"

# The 5 off_ave_lot zones from src/lib/inventory/data.ts, each with a real-world
# reference point to geocode (a named street or the avenue address of the
# anchor business the zone is described against).
ZONES = [
    {"id": "lot-cvs-mason", "est": 58,
     "name": "Rear lot near CVS / USPS / Le Penguin (Mason St side)",
     "ref": "99 Greenwich Avenue, Greenwich, CT, USA"},
    {"id": "lot-benedict-lewis", "est": 145,
     "name": "Benedict Place / Lewis Street municipal lot",
     "ref": "Benedict Place, Greenwich, CT, USA"},
    {"id": "lot-saks-mason", "est": 115,
     "name": "Saks / Posh Nails / Fieldpoint Private / Mason St rear lots",
     "ref": "205 Greenwich Avenue, Greenwich, CT, USA"},
    {"id": "lot-happymonkey-eastend", "est": 60,
     "name": "Rear lots near Happy Monkey / Jean-Georges / Eastend",
     "ref": "409 Greenwich Avenue, Greenwich, CT, USA"},
    {"id": "lot-moli", "est": 65,
     "name": "Rear lots behind MOLI / Core Burn / Charles Hilton",
     "ref": "289 Greenwich Avenue, Greenwich, CT, USA"},
]


def haversine_m(a, b):
    lat1, lon1, lat2, lon2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    d = (math.sin((lat2 - lat1) / 2) ** 2
         + math.cos(lat1) * math.cos(lat2) * math.sin((lon2 - lon1) / 2) ** 2)
    return 2 * 6371000 * math.asin(math.sqrt(d))


def confidence(m: float) -> str:
    return "HIGH" if m < 80 else "MEDIUM" if m < 150 else "LOW"


def gmaps(lat, lon) -> str:
    return f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"


def main() -> None:
    pub = [l for l in LOTS["lots"] if l["candidatePublic"]]

    lines = ["# Lot curation worksheet (PROPOSED — verify each match)\n"]
    lines.append("Generated by `analysis/lot_curation.py`. Each inventory public "
                 "lot is matched to the nearest OSM public-candidate lot by "
                 "geocoding its reference. **These are proposals, not facts** — "
                 "OSM has no access tags, so confirm on a map before editing "
                 "`src/lib/inventory/data.ts`.\n")

    lines.append("## Proposed matches\n")
    lines.append("| inventory zone | hand est | nearest OSM lot | OSM spaces | gap m | conf | map |")
    lines.append("|---|---|---|---|---|---|---|")
    used = {}
    rows = []
    for z in ZONES:
        try:
            lat, lon = ox.geocode(z["ref"])
        except Exception as e:  # noqa: BLE001
            lines.append(f"| {z['name']} | {z['est']} | geocode failed: {e} | | | | |")
            continue
        nearest = min(pub, key=lambda l: haversine_m((lat, lon), (l["lat"], l["lon"])))
        m = haversine_m((lat, lon), (nearest["lat"], nearest["lon"]))
        used[nearest["id"]] = used.get(nearest["id"], 0) + 1
        rows.append((z, nearest, m))
        lines.append(
            f"| {z['name']} | {z['est']} | `{nearest['id']}` ({nearest['blockId']}) "
            f"| {nearest['derivedSpaces']} | {m:.0f} | {confidence(m)} "
            f"| [map]({gmaps(nearest['lat'], nearest['lon'])}) |"
        )

    dupes = {k: v for k, v in used.items() if v > 1}
    if dupes:
        lines.append("\n> ⚠ Some zones matched the SAME OSM lot "
                     f"({', '.join(dupes)}). The inventory may bundle multiple "
                     "physical lots into one zone, or two zones share a lot. Split "
                     "by hand.\n")

    matched_ids = {n["id"] for _, n, _ in rows}
    lines.append("\n## All OSM public-candidate lots (for reference)\n")
    lines.append("| OSM id | block | spaces | area m² | dist to Ave | matched? | map |")
    lines.append("|---|---|---|---|---|---|---|")
    for l in sorted(pub, key=lambda x: -x["derivedSpaces"]):
        mark = "✓" if l["id"] in matched_ids else "—"
        lines.append(
            f"| `{l['id']}` | {l['blockId']} | {l['derivedSpaces']} | {l['areaM2']:.0f} "
            f"| {l['distToAveM']:.0f} m | {mark} | [map]({gmaps(l['lat'], l['lon'])}) |"
        )

    inv_total = sum(z["est"] for z in ZONES)
    matched_total = sum(n["derivedSpaces"] for _, n, _ in rows)
    lines.append(f"\n## Totals\n")
    lines.append(f"- Inventory public total (hand): **{inv_total}** spaces")
    lines.append(f"- Matched OSM lots (measured): **{matched_total}** spaces "
                 f"across {len(matched_ids)} distinct lots")
    lines.append(f"- All OSM public-candidate footprint: "
                 f"**{sum(l['derivedSpaces'] for l in pub)}** spaces ({len(pub)} lots)")
    lines.append("\nThe matched total is the apples-to-apples comparison to the "
                 "hand estimate. The full candidate footprint stays larger because "
                 "it still includes big private/commercial lots.\n")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    for z, n, m in rows:
        print(f"  {z['id']:<24} -> {n['id']:<14} {n['derivedSpaces']:>3} sp "
              f"(est {z['est']}) {m:.0f}m {confidence(m)}")


if __name__ == "__main__":
    main()
